#!/usr/bin/env python3
"""Validate editable research data and build the static browser bundle."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
registry=json.loads((ROOT/'data/registry.json').read_text())
index=json.loads((ROOT/'data/source-index.json').read_text())
assert len({r['id'] for r in registry})==len(registry),'Duplicate record ID'
assert len({r['id'] for r in index})==len(index),'Duplicate source ID'
vins=[]
for r in registry:
 assert r['tier']!='unknown','Population placeholders are not research records'
 assert r['record_kind'] in ('profile','lead','prototype')
 assert r['sources'] and all(s[1].startswith('https://') for s in r['sources'])
 assert len(r['photos'])==len(r['photo_sources'])==len(r['photo_captions'])==len(r['credits']),(r['id'],'Missing photo credit')
 for p in r['photos']:
  assert p.startswith('https://') or (p.startswith('assets/photos/') and (ROOT/p).is_file()),p
 if r['vin'].startswith('ZFF'):
  assert re.fullmatch(r'ZFF[A-HJ-NPR-Z0-9]{14}',r['vin']),r['vin']
  vins.append(r['vin'])
 if r['record_kind']=='prototype':assert 'Original 599' not in r['edition']
assert len(vins)==len(set(vins)),'Duplicate VIN'
for r in index:
 assert r['source_url']=='https://exclusivecarregistry.com/details/ferrari/daytona-sp3/'+r['id'].removeprefix('ECR-')
 assert r['thumbnail'].startswith('https://exclusivecarregistry.com/')
assert len(index)==503,'Update snapshot count and page copy when refreshing index'
serialize=lambda x:json.dumps(x,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
(ROOT/'assets/data.js').write_text('// Generated by scripts/build.py; edit data/*.json instead.\nconst bundled='+serialize(registry)+';\nconst sourceIndex='+serialize(index)+';\n')
print(f'Validated: {len(registry)} research records, {len(vins)} VINs, {len(index)} public source links.')
